# -*- coding: utf-8 -*-
"""주택가격 그룹화.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jnuuLwr-Znd9WzJw42yf4clth5djRfPF
"""

#한글폰트설치
!apt-get install fonts-nanum -qq > /dev/null
!fc-cache -fv
import matplotlib as mpl
mpl.font_manager._rebuild()
findfont = mpl.font_manager.fontManager.findfont
mpl.font_manager.findfont = findfont
mpl.backends.backend_agg.findfont = findfont
plt.rcParams['axes.unicode_minus'] = False
import matplotlib.font_manager
font_list = matplotlib.font_manager.findSystemFonts(fontpaths=None, fontext='ttf')
[matplotlib.font_manager.FontProperties(fname=font).get_name() for font in font_list if 'Nanum' in font]

#라이브러리 불러오기
!git clone https://github.com/JupiterHJ/Korea_homeprice_group.git

#데이터 읽어오기
import pandas as pd
df = pd.read_csv('/content/Korea_homeprice_group/평균매매가격.csv', encoding='UTF8', index_col=0)

#데이터 자료형 확인하기
print(df.info())
print(df.dtypes)

#float로 뜨게 자료형 데이터 변경
df = df.apply(pd.to_numeric, errors='coerce')
print(df.info())
print(df.dtypes)

"""# **1. 주택가격 흐름이 비슷한 지역 찾기**"""

#1.지역입력하기
import numpy as np

name = input('원하는 지역 이름을 입력해주세요. (예: 구로구) : ')
a = df.index.str.contains(name)   #a = df.index.str.contains(name)
df2 = df[a]
df2

#2. 그래프로 시각화하기
import matplotlib.pyplot as plt

#빼고(sub) 제곱값(power)을 모두 더함(sum), sort_values(정렬)
i = input('몇 개의 지역까지 나타내시겠습니까? (예:5) : ')
plt.rc('font', family='NanumGothic')
df.loc[np.power(df.sub(df2.iloc[0], axis=1), 2).sum(axis=1).sort_values().index[:int(i)]].T.plot()
plt.show()

"""# 2. 실거래가 확인하기
 - https://eslife.tistory.com/1100


# 3. 주택가격 싸이클이 비슷한 구간 찾기

"""